# Generated by Django 4.1.3 on 2022-12-12 23:07

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.indexes.unique_index


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("givenName", models.TextField(max_length=80)),
                ("lastName", models.TextField(default="", max_length=80)),
                ("fullName", models.TextField(max_length=256, unique=True)),
                ("url", models.TextField(max_length=1024)),
            ],
            options={
                "ordering": ["lastName"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=256, unique=True)),
                ("url", models.TextField(max_length=1024)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.actor"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.movie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(through="api.MovieActor", to="api.actor"),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=psqlextra.indexes.unique_index.UniqueIndex(
                fields=["fullName"], name="api_actor_fullNam_83ffc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=psqlextra.indexes.unique_index.UniqueIndex(
                fields=["title"], name="api_movie_title_f63d7e_idx"
            ),
        ),
    ]
